---
- hosts: genkifitness_front
  pre_tasks:
      - name: update apt cache if needed.
        become: yes
        become_method: sudo
        apt: update_cache=yes cache_valid_time=3600
  tasks:
      - name: 安装用于管理apt源工具
        become: yes
        become_method: sudo
        apt: name={{item}} state=present
        with_items:
            - python-apt
            - python-pycurl
            - python-mysqldb
      - name: 添加php的ondrej源
        become: yes
        become_method: sudo
        apt_repository: repo='ppa:ondrej/php' update_cache=yes
      - name: 安装 nginx,mysql,php 以及拓展依赖
        become: yes
        become_method: sudo
        apt: name={{ item }} state=present
        with_items:
             -  git
             -  curl
             -  nginx
             -  php7.2
             -  php7.2-cli
             -  php7.2-common
             -  php7.2-curl
             -  php7.2-fpm
             -  php7.2-gd
             -  php7.2-json
             -  php7.2-mbstring
             -  php7.2-mysql
             -  php7.2-opcache
             -  php7.2-readline
             -  php7.2-xml
             -  php7.2-xmlrpc
             -  php7.2-zip
             -  openssl
             -  mysql-server
             -  mysql-client
             -  libcurl4-openssl-dev
             -  sendmail
             -  sendmail-cf
      - name: "stop ufw"
        become: yes
        become_method: sudo
        service: name=ufw state=stopped
      - name: backup oldnginxconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/nginx /etc/nginx.bak
      - name: backup oldphpconfig
        become: yes
        become_method: sudo
        shell: >
           mv /etc/php/7.2 /etc/php/7.2.bak
      - name: Extract nginxconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "http://nighslee.com/ni/nginx.tar.gz"
           dest: "/etc/"
           remote_src: yes
      - name: Extract phpconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "http://nighslee.com/ni/7.2.tar.gz"
           dest: "/etc/php"
           remote_src: yes
      - name: Extract sslconfig into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "http://nighslee.com/ni/www.nighslee.com.tar.gz"
           dest: "/etc/ssl"
           remote_src: yes
      - name: Extract appsrc into dir
        become: yes
        become_method: sudo
        unarchive:
           src: "http://nighslee.com/ni/nighslee.tar.gz"
           dest: "/home/crazysal"
           group: crazysal
           owner: crazysal
           remote_src: yes
      - name: start memcache,nginx,php
        become: yes
        become_method: sudo
        service: "name={{ item }} state=started enabled=yes"
        with_items:
             - nginx
             - php7.2-fpm

